### ISSUE TITLE
Add 'io-console' gem to Gemfile

### ISSUE THREAD

**Issue by Goorzhel** [chrisvfritz/tc359_helper_methods#1]
`guard` requires the gem `io-console` through `thor`. Without it, this happens:

```
[12:15 ~/tc359/p8] % bundle exec guard
/home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:2:in `require': cannot load such file -- io/console (LoadError)
        from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:2:in `<top (required)>'
        from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.1/lib/thor/shell/color.rb:1:in `require'
        from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.1/lib/thor/shell/color.rb:1:in `<top (required)>'
        from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.1/lib/thor/shell.rb:17:in `shell'
        from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.1/lib/thor/base.rb:439:in `start'
        from /home/ec2-user/.gem/ruby/2.0/gems/guard-2.12.1/lib/guard/aruba_adapter.rb:32:in `execute'
        from /home/ec2-user/.gem/ruby/2.0/gems/guard-2.12.1/lib/guard/aruba_adapter.rb:19:in `execute!'
        from /home/ec2-user/.gem/ruby/2.0/gems/guard-2.12.1/bin/_guard-core:11:in `<main>'
```

**Comment by chrisvfritz** [comment]
Hmm, it looks like this might be a problem [unique to AWS servers](http://stackoverflow.com/questions/23184819/rails-new-app-or-rails-h-craps-out-with-cannot-load-such-file-io-console).

**Comment by Goorzhel** [comment]
A-whoops. Fun being the only one without a laptop, eh? :P

**Comment by chrisvfritz** [comment]
:smiley: Hey, you get to learn more though, right?
